version: '3'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: user-db
    ports:
      - "5433:5432"
    volumes:
      - my-db:/var/lib/postgresql
    networks:
      my_net:
    
  db-device:
    image: postgres
    container_name: db-device
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: device-db
    ports:
      - "5434:5432"
    volumes:
      - my-db-device:/var/lib/postgresql
    networks:
      my_net:

  db-auth:
    image: postgres
    container_name: db-auth
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth-db
    ports:
      - "5435:5432"
    volumes:
      - my-db-auth:/var/lib/postgresql
    networks:
      my_net:

  db-monitoring:
    image: postgres
    container_name: db-monitoring
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: monitoring-db
    ports:
      - "5436:5432"
    volumes:
      - my-db-monitoring:/var/lib/postgresql
    networks:
      my_net:

  db-chat:
    image: postgres
    container_name: db-chat
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: chat-db
    ports:
      - "5437:5432"
    volumes:
      - my-db-chat:/var/lib/postgresql
    networks:
      my_net:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"  
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - my_net
    

  nginx: 
    build:
      context: ./nginx # Calea cÄƒtre folderul cu Dockerfile-ul frontend-ului
      dockerfile: Dockerfile
    container_name: nginx-frontend
    restart: unless-stopped
    networks:
      - my_net


  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: always
    ports:
      - "80:80" # The HTTP port
      # - "443:443" # The HTTPS port
      - "8080:8080" # Dashboard port
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # Traefik can listen to the Docker events
      - "./traefik.yml:/etc/traefik/traefik.yml:ro" # Static configuration file
      - "./dynamic:/etc/traefik/dynamic:ro" # Dynamic configuration files
      - "./logs:/var/log/traefik" # Log files
    develop: # Enable live reload of dynamic configuration files on Windows, if using Unix based system needs to be commented out
      watch:
        - path: ./dynamic                   # watch the whole folder
          action: restart
    networks:
      - my_net

  spring-monitoring:
    build:
      context: ./monitoring-backend 
      dockerfile: ./Dockerfile
    #container_name: spring-monitoring
    ports:
      - "8084:8080"
    environment:
      - DB_IP=db-monitoring
      - DB_PORT=5432
      - DB_DBNAME=monitoring-db
      - DB_USER=postgres
      - DB_PASSWORD=root
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - TZ=Europe/Bucharest
    networks:
      my_net:
    depends_on:
      - db-monitoring
      - rabbitmq
    command: /bin/sh -c "echo 'Waiting for RabbitMQ to start...'; sleep 20 && exec java -jar /demo/demo.jar"
      


  spring-demo:
    build:
      context: ./demo
      dockerfile: ./Dockerfile
    container_name: spring-demo
    ports:
      - "8081:8080"
    environment:
      - DB_IP=db
      - DB_PORT=5432
      - DB_DBNAME=user-db
      - DB_USER=postgres
      - DB_PASSWORD=root
    networks:
      my_net:
    depends_on:
      - rabbitmq
    command: /bin/sh -c "echo 'Waiting for RabbitMQ to start...'; sleep 20 && exec java -jar /demo/demo.jar"

  spring-device:
    build:
      context: ./device-backend
      dockerfile: ./Dockerfile
    container_name: spring-device
    ports:
      - "8082:8080"
    environment:
      - DB_IP=db-device
      - DB_PORT=5432
      - DB_DBNAME=device-db
      - DB_USER=postgres
      - DB_PASSWORD=root
    networks:
      my_net:
    depends_on:
      - rabbitmq
    command: /bin/sh -c "echo 'Waiting for RabbitMQ to start...'; sleep 20 && exec java -jar /demo/demo.jar"

  spring-auth:
    build:
      context: ./auth-backend
      dockerfile: ./Dockerfile
    container_name: spring-auth
    ports:
      - "8083:8080"
    environment:
      - DB_IP=db-auth
      - DB_PORT=5432
      - DB_DBNAME=auth-db
      - DB_USER=postgres
      - DB_PASSWORD=root
    networks:
      my_net:
    depends_on:
      - rabbitmq
    command: /bin/sh -c "echo 'Waiting for RabbitMQ to start...'; sleep 20 && exec java -jar /demo/demo.jar"

  spring-websocket:
    build:
      context: ./websocket-backend
      dockerfile: ./Dockerfile
    ports:
      - "8085:8080"
    environment:
      - DB_IP=db-chat
      - DB_PORT=5432
      - DB_DBNAME=chat-db
      - DB_USER=postgres
      - DB_PASSWORD=root
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - TZ=Europe/Bucharest
    networks:
      my_net:
    depends_on:
      - rabbitmq
      - db-chat
    command: /bin/sh -c "echo 'Waiting for RabbitMQ to start...'; sleep 20 && exec java -jar /demo/demo.jar"


volumes:
  my-db:
  my-db-device:
  my-db-auth:
  my-db-monitoring:
  rabbitmq_data:
  my-db-chat:

networks:
  my_net:
    external: true
